# Generated by Django 3.0.8 on 2020-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNum',
            field=models.IntegerField(default=12),
        ),
    ]
